_target_: project.tasks.unlearning_atu.UnlearningATU
_recursive_: false

name: unlearning-atu

defaults:
  - /text_encoder@text_encoder: all-mpnet-base-v2
  - /embedding_prediction_model@embedding_prediction_model: transformer
  - /data@unlearning_data: rwku-positive

training_module:
  training_warmup_steps: 2000
  training_lr: 0.0001
  training_weight_decay: 0.0
  unlearning_lr: 0.0003
  unlearning_weight_decay: 0.0
  pretrained_model_hook_layer: 29
  clip_grad_norm: 1.0

num_other_targets: 3

first_stage_steps: 15000

stages:
  - type: "training"
    steps: ${task.first_stage_steps}
  - type: "unlearning"
    threshold: 0.9
    steps: 1000
  - type: "training"
    steps: 1000
  - type: "unlearning"
    threshold: 0.8
    steps: 1000
  - type: "training"
    steps: 1000
  - type: "unlearning"
    threshold: 0.75
    steps: 1000
  - type: "training"
    steps: 1000
  - type: "unlearning"
    threshold: 0.7
    steps: 1000
  - type: "training"
    steps: 1000
  - type: "unlearning"
    threshold: 0.65
    steps: 1000
  - type: "training"
    steps: 1000
  - type: "unlearning"
    threshold: 0.6
    steps: 1000
  - type: "training"
    steps: 1000
  - type: "unlearning"
    threshold: 0.5
    steps: 1000
  - type: "training"
    steps: 1000
  - type: "unlearning"
    threshold: 0.4
    steps: 1000
  - type: "training"
    steps: 1000
  - type: "unlearning"
    threshold: 0.3
    steps: 1000
  - type: "training"
    steps: 1000
  - type: "unlearning"
    threshold: 0.2
    steps: 1000